# .swiftlint.yml

included:
  - WebViewBrowser
  - AppProxyExtension

excluded:
  - Pods
  - Carthage
  - .build

# 核心策略：只把严重问题设为 error
opt_in_rules:
  - force_unwrapping

disabled_rules:
  - trailing_whitespace
  - todo # 忽略 TODO 标记
  - identifier_name # 允许短变量名 i, d, t 等
  - large_tuple # 允许大元组
  - cyclomatic_complexity # 允许复杂函数
  - function_parameter_count # 允许多参数函数

# 所有规则设为 warning，不中断构建（只做代码风格提示）
force_cast: warning
force_try: warning
force_unwrapping: warning
line_length: warning
file_length: warning
type_body_length: warning
function_body_length: warning
